# 配置文件模板
app:
  #app工程路径
  project_path: ../../
  #app主module名称(名称和路径需要保持一致)
  main_module: app
  #更新描述前缀,会添加 在更新描述之前
  update_desc_prefix: "饿了么更新了!\n更新描述:\n"
  #gradle 打包脚本
  build_command: 'gradlew app:clean app:assembleDebug'
# pgyer 的api配置
pgyer:
  # Api Key
  api_key: xxxxxxxxxxxxxxxxxxxxxx
  # App Key
  app_key: xxxxxxxxxxxxxxxxxxxxxx
  # User Key
  u_key: xxxxxxxxxxxxxxxxxxxxxx

# 钉钉
dingding:
  # 群机器人 token
  access_token: xxxxxxxxxxxxxxxxxxxxxx